// Static, authored list of example Experiences from the Daggerheart SRD (Character Creation,
// Step 7 "Create Your Experiences"). Surfaced as optional, tappable suggestions in the builder
// (CBW-12). These are inspiration only — the player types their own Experience text; there is no
// canonical Experience list in the SRD. Source: Daggerheart SRD v1.0 (2025-09-09), printed page 5.

export type ExperienceSuggestionCategory = {
  label: string;
  examples: string[];
};

export const experienceSuggestions: ExperienceSuggestionCategory[] = [
  {
    label: "Backgrounds",
    examples: [
      "Assassin",
      "Blacksmith",
      "Bodyguard",
      "Bounty Hunter",
      "Chef to the Royal Family",
      "Circus Performer",
      "Con Artist",
      "Fallen Monarch",
      "Field Medic",
      "High Priestess",
      "Merchant",
      "Noble",
      "Pirate",
      "Politician",
      "Runaway",
      "Scholar",
      "Sellsword",
      "Soldier",
      "Storyteller",
      "Thief",
      "World Traveler",
    ],
  },
  {
    label: "Characteristics",
    examples: [
      "Affable",
      "Battle-Hardened",
      "Bookworm",
      "Charming",
      "Cowardly",
      "Friend to All",
      "Helpful",
      "Intimidating Presence",
      "Leader",
      "Lone Wolf",
      "Loyal",
      "Observant",
      "Prankster",
      "Silver Tongue",
      "Sticky Fingers",
      "Stubborn to a Fault",
      "Survivor",
      "Young and Naive",
    ],
  },
  {
    label: "Specialties",
    examples: [
      "Acrobat",
      "Gambler",
      "Healer",
      "Inventor",
      "Magical Historian",
      "Mapmaker",
      "Master of Disguise",
      "Navigator",
      "Sharpshooter",
      "Survivalist",
      "Swashbuckler",
      "Tactician",
    ],
  },
  {
    label: "Skills",
    examples: [
      "Animal Whisperer",
      "Barter",
      "Deadly Aim",
      "Fast Learner",
      "Incredible Strength",
      "Liar",
      "Light Feet",
      "Negotiator",
      "Photographic Memory",
      "Quick Hands",
      "Repair",
      "Scavenger",
      "Tracker",
    ],
  },
  {
    label: "Phrases",
    examples: [
      "Catch Me If You Can",
      "Fake It Till You Make It",
      "First Time’s the Charm",
      "Hold the Line",
      "I Won’t Let You Down",
      "I’ll Catch You",
      "I’ve Got Your Back",
      "Knowledge Is Power",
      "Nature’s Friend",
      "Never Again",
      "No One Left Behind",
      "Pick on Someone Your Own Size",
      "The Show Must Go On",
      "This Is Not a Negotiation",
      "Wolf in Sheep’s Clothing",
    ],
  },
];
