import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";
import { SrdEntryCollectionSchema, type SrdEntry } from "../src/srd/schema";

const execFileAsync = promisify(execFile);

const sourcePdfPath = "data/source/Daggerheart-SRD-9-09-25.pdf";
const outputPath = "data/srd/generated/entries.candidates.json";

const source = {
  document: "Daggerheart SRD" as const,
  version: "1.0-2025-09-09",
  pdf: {
    path: sourcePdfPath,
    pageStart: 20,
    pageEnd: 20,
  },
  printedPages: [38, 39],
  url: "https://www.daggerheart.com/wp-content/uploads/2025/09/Daggerheart-SRD-9-09-25.pdf",
};

const commonReview = {
  status: "extracted" as const,
  reviewedAt: null,
  notes: ["Generated by scripts/extract-rule-references.ts from pdftotext -raw; review spacing and wording against the source PDF."],
};

const headingSpecs = [
  {
    id: "rule.core.hope_fear",
    name: "Hope & Fear",
    slug: "hope-fear",
    heading: "HOPE & FEAR",
    nextHeading: "HOPE",
    summary: "Introduces Hope and Fear as player and GM metacurrencies.",
    tags: ["rule", "core", "hope", "fear", "metacurrency"],
    headings: ["Core Mechanics", "Hope & Fear"],
  },
  {
    id: "rule.core.hope",
    name: "Hope",
    slug: "hope",
    heading: "HOPE",
    nextHeading: "FEAR",
    summary: "Player metacurrency used to help allies, use experiences, initiate Tag Team Rolls, and activate Hope Features.",
    tags: ["rule", "core", "hope", "metacurrency"],
    headings: ["Core Mechanics", "Hope & Fear", "Hope"],
  },
  {
    id: "rule.core.fear",
    name: "Fear",
    slug: "fear",
    heading: "FEAR",
    nextHeading: "COMBAT",
    summary: "GM metacurrency gained from rolls with Fear and spent on GM moves and Fear Features.",
    tags: ["rule", "core", "fear", "metacurrency"],
    headings: ["Core Mechanics", "Hope & Fear", "Fear"],
  },
] satisfies Array<{
  id: string;
  name: string;
  slug: string;
  heading: string;
  nextHeading: string;
  summary: string;
  tags: string[];
  headings: string[];
}>;

const rawText = await extractPdfPage(sourcePdfPath, 20);
const entries = headingSpecs.map((spec) => ({
  id: spec.id,
  kind: "rule_reference" as const,
  name: spec.name,
  slug: spec.slug,
  source,
  review: commonReview,
  text: {
    original: extractSection(rawText, spec.heading, spec.nextHeading),
    summary: spec.summary,
  },
  tags: spec.tags,
  relationships: [],
  category: "core mechanics",
  headings: spec.headings,
})) satisfies SrdEntry[];

SrdEntryCollectionSchema.parse(entries);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(resolve(process.cwd(), outputPath), `${JSON.stringify(entries, null, 2)}\n`, "utf8");

console.log(`Extracted ${entries.length} rule_reference candidate entries to ${outputPath}.`);

async function extractPdfPage(pdfPath: string, page: number) {
  const { stdout } = await execFileAsync("pdftotext", ["-raw", "-f", String(page), "-l", String(page), pdfPath, "-"]);
  return stdout;
}

function extractSection(rawText: string, heading: string, nextHeading: string) {
  const lines = rawText.split(/\r?\n/);
  const startIndex = lines.findIndex((line) => line.trim() === heading);

  if (startIndex === -1) {
    throw new Error(`Could not find heading: ${heading}`);
  }

  const nextIndex = lines.findIndex((line, index) => index > startIndex && line.trim() === nextHeading);

  if (nextIndex === -1) {
    throw new Error(`Could not find next heading after ${heading}: ${nextHeading}`);
  }

  return normalizeExtractedLines(lines.slice(startIndex + 1, nextIndex));
}

function normalizeExtractedLines(lines: string[]) {
  return lines
    .map((line) => line.trim())
    .filter(Boolean)
    .join(" ")
    .replace(/\s+/g, " ");
}
