import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";
import { SrdEntryCollectionSchema, type SrdEntry } from "../src/srd/schema";

const execFileAsync = promisify(execFile);

const sourcePdfPath = "data/source/Daggerheart-SRD-9-09-25.pdf";
const outputPath = "data/srd/generated/weapons.candidates.json";
const reviewReportPath = "data/srd/generated/weapons-review-report.md";
const sourceUrl = "https://www.daggerheart.com/wp-content/uploads/2025/09/Daggerheart-SRD-9-09-25.pdf";
const pdfPage = 23;
const printedPages = [44, 45];

type WeaponEntry = Extract<SrdEntry, { kind: "weapon" }>;

type TextBox = {
  top: number;
  left: number;
  text: string;
};

type WeaponRow = {
  entry: WeaponEntry;
  warnings: string[];
  rowTop: number;
};

const xml = await extractWeaponPageXml(sourcePdfPath);
const rows = extractWeaponRows(parseTextBoxes(xml));
const entries = rows.map((row) => row.entry);

SrdEntryCollectionSchema.parse(entries);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(resolve(process.cwd(), outputPath), `${JSON.stringify(entries, null, 2)}\n`, "utf8");
await writeFile(resolve(process.cwd(), reviewReportPath), buildReviewReport(rows), "utf8");

console.log(`Extracted ${entries.length} weapon candidate entries to ${outputPath}.`);
console.log(`Wrote weapon review report to ${reviewReportPath}.`);

async function extractWeaponPageXml(pdfPath: string) {
  const { stdout } = await execFileAsync("pdftohtml", ["-xml", "-f", String(pdfPage), "-l", String(pdfPage), "-stdout", pdfPath]);
  return stdout;
}

function parseTextBoxes(xmlText: string) {
  const boxes: TextBox[] = [];
  const textPattern = /<text\s+top="(?<top>\d+)"\s+left="(?<left>\d+)"[^>]*>(?<text>[\s\S]*?)<\/text>/g;

  for (const match of xmlText.matchAll(textPattern)) {
    const groups = match.groups;
    if (!groups) {
      continue;
    }

    const text = decodeXml(stripTags(groups.text ?? "")).trim();
    if (!text) {
      continue;
    }

    boxes.push({
      top: Number(groups.top),
      left: Number(groups.left),
      text,
    });
  }

  return boxes.sort((a, b) => a.top - b.top || a.left - b.left);
}

function extractWeaponRows(boxes: TextBox[]) {
  const rowStarts = boxes.filter((box) => isTraitBox(box));
  const rows: WeaponRow[] = [];

  for (const [index, traitBox] of rowStarts.entries()) {
    const nextRowTop = rowStarts[index + 1]?.top ?? 1050;
    const weaponType = traitBox.top < 640 ? "physical" : "magic";
    const rowEndTop = Math.min(nextRowTop, weaponType === "physical" ? 640 : 1050);
    const name = extractColumnText(boxes, traitBox.top, rowEndTop, [1025, 1110]);
    const rangeText = findNearbyBox(boxes, traitBox, [1195, 1265])?.text ?? "";
    const damageText = findNearbyBox(boxes, traitBox, [1275, 1345])?.text ?? "";
    const burdenText = findNearbyBox(boxes, traitBox, [1375, 1450])?.text ?? "";
    const featureText = extractColumnText(boxes, traitBox.top, rowEndTop, [1470, 1760]) || "—";
    const damage = parseDamage(damageText);
    const feature = parseFeature(featureText);
    const warnings = detectWarnings(name, traitBox.text, rangeText, damageText, burdenText, featureText, weaponType);

    rows.push({
      entry: {
        id: `weapon.primary.tier1.${toIdPart(name)}`,
        kind: "weapon",
        name,
        slug: toSlug(name),
        source: {
          document: "Daggerheart SRD",
          version: "1.0-2025-09-09",
          pdf: {
            path: sourcePdfPath,
            pageStart: pdfPage,
            pageEnd: pdfPage,
          },
          printedPages,
          url: sourceUrl,
        },
        review: {
          status: "extracted",
          reviewedAt: null,
          notes: ["Generated by scripts/extract-weapons.ts from pdftohtml -xml; review row values against the source PDF."],
        },
        text: {
          original: `${name} ${traitBox.text} ${rangeText} ${damageText} ${burdenText} ${featureText}`,
          summary: `Tier 1 ${weaponType} primary weapon with ${rangeText} range and ${damage.dice} ${damage.type} damage.`,
        },
        tags: ["weapon", "primary", "tier-1", weaponType, toSlug(rangeText), ...(feature ? [toSlug(feature.name)] : [])],
        relationships: [],
        category: "primary",
        tier: 1,
        levelRange: { min: 1, max: 1 },
        weaponType,
        requiresSpellcastTrait: weaponType === "magic",
        trait: normalizeTrait(traitBox.text),
        range: normalizeRange(rangeText),
        damage,
        burden: normalizeBurden(burdenText),
        feature,
      },
      warnings,
      rowTop: traitBox.top,
    });
  }

  return rows.sort((a, b) => a.rowTop - b.rowTop || a.entry.name.localeCompare(b.entry.name));
}

function isTraitBox(box: TextBox) {
  return box.left >= 1118 && box.left <= 1185 && isTrait(box.text) && box.top >= 270 && box.top <= 1030;
}

function isTrait(text: string) {
  return ["Agility", "Strength", "Finesse", "Instinct", "Presence", "Knowledge"].includes(text);
}

function extractColumnText(boxes: TextBox[], rowTop: number, nextRowTop: number, leftRange: [number, number]) {
  const columnBoxes = boxes.filter((box) => box.top >= rowTop - 2 && box.top < nextRowTop - 2 && box.left >= leftRange[0] && box.left <= leftRange[1]);
  const lines = new Map<number, TextBox[]>();

  for (const box of columnBoxes) {
    const lineTop = [...lines.keys()].find((top) => Math.abs(top - box.top) <= 2) ?? box.top;
    lines.set(lineTop, [...(lines.get(lineTop) ?? []), box]);
  }

  return [...lines.entries()]
    .sort(([a], [b]) => a - b)
    .map(([, lineBoxes]) =>
      lineBoxes
        .sort((a, b) => a.left - b.left)
        .map((box) => box.text)
        .join("")
        .trim(),
    )
    .join(" ")
    .replace(/\s+/g, " ")
    .replace(/:\s*/g, ": ")
    .trim();
}

function findNearbyBox(boxes: TextBox[], rowStart: TextBox, leftRange: [number, number]) {
  return boxes.find(
    (box) => box.top >= rowStart.top - 2 && box.top <= rowStart.top + 4 && box.left >= leftRange[0] && box.left <= leftRange[1],
  );
}

function parseDamage(text: string) {
  const match = text.match(/^(?<dice>d\d+(?:[+]\d+)?)\s+(?<type>phy|mag)$/);
  if (!match?.groups) {
    return { dice: "d4", type: "physical" as const };
  }

  return {
    dice: match.groups.dice ?? "d4",
    type: match.groups.type === "mag" ? ("magic" as const) : ("physical" as const),
  };
}

function parseFeature(text: string) {
  if (text === "—") {
    return null;
  }

  const colonIndex = text.indexOf(":");
  if (colonIndex === -1) {
    return { name: "Feature", text };
  }

  return {
    name: text.slice(0, colonIndex).trim(),
    text: text.slice(colonIndex + 1).trim(),
  };
}

function normalizeTrait(text: string) {
  switch (text) {
    case "Agility":
      return "agility" as const;
    case "Strength":
      return "strength" as const;
    case "Finesse":
      return "finesse" as const;
    case "Instinct":
      return "instinct" as const;
    case "Presence":
      return "presence" as const;
    case "Knowledge":
      return "knowledge" as const;
    default:
      throw new Error(`Unsupported trait: ${text}`);
  }
}

function normalizeRange(text: string) {
  switch (text) {
    case "Melee":
      return "melee" as const;
    case "Very Close":
      return "very_close" as const;
    case "Close":
      return "close" as const;
    case "Far":
      return "far" as const;
    case "Very Far":
      return "very_far" as const;
    default:
      throw new Error(`Unsupported range: ${text}`);
  }
}

function normalizeBurden(text: string) {
  switch (text) {
    case "One-Handed":
      return "one_handed" as const;
    case "Two-Handed":
      return "two_handed" as const;
    default:
      throw new Error(`Unsupported burden: ${text}`);
  }
}

function detectWarnings(
  name: string,
  traitText: string,
  rangeText: string,
  damageText: string,
  burdenText: string,
  featureText: string,
  weaponType: "physical" | "magic",
) {
  const warnings: string[] = [];

  if (!name) {
    warnings.push("Missing weapon name.");
  }

  if (!isTrait(traitText)) {
    warnings.push("Missing or malformed trait cell.");
  }

  if (!["Melee", "Very Close", "Close", "Far", "Very Far"].includes(rangeText)) {
    warnings.push("Missing or malformed range cell.");
  }

  if (!/^d\d+(?:[+]\d+)?\s+(?:phy|mag)$/.test(damageText)) {
    warnings.push("Missing or malformed damage cell.");
  }

  if (!["One-Handed", "Two-Handed"].includes(burdenText)) {
    warnings.push("Missing or malformed burden cell.");
  }

  if (weaponType === "physical" && !damageText.endsWith("phy")) {
    warnings.push("Physical weapon section has non-physical damage type.");
  }

  if (weaponType === "magic" && !damageText.endsWith("mag")) {
    warnings.push("Magic weapon section has non-magic damage type.");
  }

  if (featureText !== "—" && !featureText.includes(":")) {
    warnings.push("Feature text does not contain a feature name separator.");
  }

  if (/\b[a-z]{2,}(?:Armor|Close|Damage|Evasion|Handed|Stress|Weapon|When)\b/.test(`${name} ${featureText}`)) {
    warnings.push("Potential joined-word artifact remains.");
  }

  if (featureText.length > 240) {
    warnings.push("Long feature text; review wrapped lines.");
  }

  return warnings;
}

function buildReviewReport(rows: WeaponRow[]) {
  const lines = [
    "# Weapon Candidate Review Report",
    "",
    "Generated by `npm run extract:srd:weapons`.",
    "",
    "## Summary",
    "",
    `- Candidate entries: ${rows.length}`,
    `- Entries with warnings: ${rows.filter((row) => row.warnings.length > 0).length}`,
    "",
    "## Entries",
    "",
  ];

  for (const row of rows) {
    lines.push(`### ${row.entry.id}`);
    lines.push("");
    lines.push(`- Name: ${row.entry.name}`);
    lines.push(`- Category: ${row.entry.category}`);
    lines.push(`- Tier: ${row.entry.tier}`);
    lines.push(`- Weapon type: ${row.entry.weaponType}`);
    lines.push(`- Physical PDF page: ${row.entry.source.pdf.pageStart}`);
    lines.push(`- Printed SRD pages: ${row.entry.source.printedPages.join(", ")}`);
    lines.push(`- Review status: ${row.entry.review.status}`);
    lines.push(`- Trait: ${row.entry.trait}`);
    lines.push(`- Range: ${row.entry.range}`);
    lines.push(`- Damage: ${row.entry.damage.dice} ${row.entry.damage.type}`);
    lines.push(`- Burden: ${row.entry.burden}`);
    lines.push(`- Feature: ${row.entry.feature ? `${row.entry.feature.name}: ${row.entry.feature.text}` : "none"}`);
    lines.push(`- Warnings: ${row.warnings.length > 0 ? row.warnings.join("; ") : "none"}`);
    lines.push("");
  }

  lines.push("## Review Guidance");
  lines.push("");
  lines.push("- Fully review rows with warnings before promotion.");
  lines.push("- Spot-check clean rows against the source table.");
  lines.push("- Keep weapon candidates separate from canonical fixtures until accepted.");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function stripTags(text: string) {
  return text.replace(/<[^>]*>/g, "");
}

function decodeXml(text: string) {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function toIdPart(value: string) {
  return value
    .toLowerCase()
    .replace(/[’']/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function toSlug(value: string) {
  return value
    .toLowerCase()
    .replace(/[’']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
